# .streamlit/secrets.toml
[connections.gsheets]

public_gsheets_url = "https://docs.google.com/spreadsheets/d/10ezNUOUpzBayqIMJWuS_zsvwklxP49zlfBWsiJI6aqI/edit#gid=0"
public_gsheets_url2 = "https://docs.google.com/spreadsheets/d/10ezNUOUpzBayqIMJWuS_zsvwklxP49zlfBWsiJI6aqI/edit#gid=939232836"
public_gsheets_url3 = "https://docs.google.com/spreadsheets/d/10ezNUOUpzBayqIMJWuS_zsvwklxP49zlfBWsiJI6aqI/edit#gid=135096406"
public_gsheets_url4 = "https://docs.google.com/spreadsheets/d/10ezNUOUpzBayqIMJWuS_zsvwklxP49zlfBWsiJI6aqI/edit#gid=193382718"
public_gsheets_url_sii = "https://docs.google.com/spreadsheets/d/1M_1YUrFm6a1ihUhQXGjsY1vwzGzGoUOYGJuE_i-4Bj8/edit#gid=95308433"
public_gsheets_url_forms = "https://docs.google.com/spreadsheets/d/10ezNUOUpzBayqIMJWuS_zsvwklxP49zlfBWsiJI6aqI/edit#gid=1941981997"
public_gsheets_url_orgs = "https://docs.google.com/spreadsheets/d/1Xv8wo9nzFrcKfjDxPZz2WDPhi-2uXNvHMDOYMTJwZeE/edit#gid=0"