name: Retrieving Book Reviews

on:
  schedule:
    # Runs every day at 16:00 UTC
    - cron: '0 16 * * *'
  workflow_dispatch: {}  # allows manual trigger

permissions:
  contents: write

jobs:
  export_book_reviews:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run exporter
        run: python database_update/book_reviews.py

      - name: Commit CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update book_reviews.csv"
          file_pattern: book_reviews.csv
