name: Post publications on Twitter

on:
  schedule:
    # Run the workflow every hour (at the 0th minute of every hour)
    - cron: '0 * * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install system dependencies (distutils)
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-distutils

    # Step 4: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        pip install pandas numpy pyzotero requests beautifulsoup4 grapheme pytz

    # Step 5: Run the Python script
    - name: Run Python Script
      env:
        API_KEY: ${{ secrets.TWITTER_API_KEY }}
        API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        python twitter_posts/twitter_posts.py
