name: Update Citation Formats

# Schedule the workflow to run once a day
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 4 * * *'  # Runs at 4 am UTC every day

jobs:
  update_csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write permissions to push changes
    steps:
      # Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true  # Ensure Git credentials persist

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      # Install necessary dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run the Python Script
      - name: Run Run Python Script
        run: |
          python database_update/all_items_citation_format_retrieval.py  # Execute the Python script

      # Pull, commit, and push changes to CSV files
      - name: Pull, commit, and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git pull origin main  # Pull the latest changes from the remote repository
          git add *.csv  # Add all CSV files in the repository
          git diff-index --quiet HEAD || git commit -m "Update Zotero data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}